export const NUEVO_REGISTRO = "NUEVO_REGISTRO";
export const BORRAR_REGISTRO = "BORRAR_REGISTRO";
export const SELECCIONAR_REGISTRO = "SELECCIONAR_REGISTRO";
export const MODIFICAR_REGISTRO = "MODIFICAR_REGISTRO";
export const FETCH_REGISTROS = "FETCH_REGISTROS";
